version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
  db:
    image: postgres:15-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: ./crm_backend
      dockerfile: Dockerfile
    ports:
      - "80"