version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://api/v1
    ports:
      - "8082:3000"
    environment:
      - VITE_API_BASE_URL=http://api
  db:
    image: postgres:15-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: ./crm_backend
      dockerfile: Dockerfile
    ports:
      - "80"