version: "3.9"
services:
  db:
    image: postgres:15-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"